version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    volumes:
      - ./config:/config
    restart: always
    ports:
      - 8123:8123
    environment:
      - TZ=America/New_York