- id: on_sunset
  alias: On Sunset
  initial_state: 'on'
  trigger:
    - platform: homeassistant
      event: start
    - platform: sun
      event: sunset
      offset: "-00:45:00"
  action:
    - service: frontend.set_theme
      data:
        name: dark
    - service: hue.hue_activate_scene
      data:
        group_name: "Living Room"
        scene_name: "Living Room"
- id: on_sunrise
  alias: On Sunrise
  initial_state: 'on'
  trigger:
    - platform: homeassistant
      event: start
    - platform: sun
      event: sunrise
  action:
    - service: frontend.set_theme
      data:
        name: default