homeassistant:
  elevation: 0
  unit_system: imperial
  time_zone: America/Chicago
  name: Home

config:
frontend:
updater:
conversation:
sun:
logbook:
recorder:
history:

hue:
  bridges:
    # You'll need to change the host below to your Hue bridge's internal IP Address at:
    # https://www.meethue.com/api/nupnp [{"internalipaddress":"192.168.1.65"}]
    - host: 192.168.1.65

#lovelace:
#  mode: yaml