homeassistant: !include hass-base/homeassistant.yaml
config:
frontend: !include hass-base/frontend.yaml
updater:
conversation:
sun:
logbook:
recorder:
history:
input_select: !include hass-base/input_select.yaml
automation: !include_dir_merge_list automations
hue: !include integrations/hue/base.yaml
august: !include integrations/august/base.yaml
weather: !include integrations/darksky/base.yaml

lovelace:
  mode: yaml