# HOME ASSISTANT
# For any location-aware items, I suggest putting a general area rather than your specific coordinates.
home_lat: YOUR_HOME_LATITUDE
home_lng: YOUR_HOME_LONGITUDE
timezone: YOUR_TIMEZONE # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# AUGUST LOCK
august_username: YOUR_EMAIL
august_password: YOUR_PASSWORD

# DARKSKY WEATHER API
# You must sign up for a darksky API key to use the weather feature in this repository (it's free).
darksky_api_key: YOUR_DARKSKY_API_KEY # https://darksky.net/dev/register

