# HOME ASSISTANT
# For any location-aware items, I suggest putting a general area rather than your specific coordinates.
home_lat: YOUR_HOME_LATITUDE
home_lng: YOUR_HOME_LONGITUDE
timezone: YOUR_TIMEZONE # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# AUGUST LOCK
august_username: YOUR_EMAIL
august_password: YOUR_PASSWORD

# HUE BRIDGE CONFIGURATION
# You'll need to change the host below to your Hue bridge's internal IP Address
# For multiple hue bridges, create a new entry here called hue_bridge_ip_address_2, and so on.
# Then in config/integrations/hue/base.yaml, add a new list item with a new host ip address
hue_bridge_ip_address: YOUR_HUE_BRIDGE_IP_ADDRESS # https://www.meethue.com/api/nupnp [{"internalipaddress":"192.168.1.65"}]

# DARKSKY WEATHER API
# You must sign up for a darksky API key to use the weather feature in this repository (it's free).
darksky_api_key: YOUR_DARKSKY_API_KEY # https://darksky.net/dev/register

